server:
  port: 8083
spring:
  application:
    name: consumer
  cloud:
    loadbalancer:
      retry:
        enabled: true #开启spring Cloud的重试功能

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka,http://localhost:10087/eureka
    #拉取服务列表，设置每隔多少秒更新数据
    registry-fetch-interval-seconds: 3
serivce: #服务名称
  ribbon:
      NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
      ConnectTimeout: 250 #Ribbon的连接超时时间
      ReadTimeout: 1000 #Ribbon的数据读取超时时间
      OkToRetryOnAllOperations: true #是否对所有操作都进行重试
      MaxAutoRetriesNextServer: 1 #切换实例的重试次数
      MaxAutoRetries: 1 #对当前实例的重试次数
logging:
  level:
    ROOT: info
feign:
  hystrix:
    enabled: true
ribbon:
  ConnectionTimeout: 2000
  RedaTimeOut: 5000

